events {
    worker_connections 1024;
}

http {
    upstream client {
        server client:80;        
    }

    upstream server {
        server server:8000;         
    }

    server {
        listen 80;
        server_name _;          

        location /api/ {
            proxy_pass http://server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /detect {
            proxy_pass http://server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            client_max_body_size 10M;    
        }

        location /images/ {
            proxy_pass http://server;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://client;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
